In [102]:
# get fundamental data
import requests

stockCode = 'AAPL'

# set api key
api = "7OVAOOPNIMKJKIAX"

r = requests.get("https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol="+stockCode+"&apikey=" + api)

In [84]:
def findNone(balance_df_):
    col = []
    for i in balance_df_.columns:
        for j in balance_df_[i]:
            if 'None' in j:
                if i in col:
                    pass
                else:
                    col.append(i)
    print(col)

In [85]:
findNone(income_df)

['effectOfAccountingCharges', 'minorityInterest', 'otherOperatingExpense', 'taxProvision', 'interestIncome', 'netInterestIncome', 'extraordinaryItems', 'nonRecurring', 'otherItems', 'discontinuedOperations', 'preferredStockAndOtherAdjustments']

In [103]:
import pandas as pd

income_df = pd.DataFrame(a)
dropCol = ['reportedCurrency', 'effectOfAccountingCharges','minorityInterest', 'netInterestIncome',\
           'extraordinaryItems', 'nonRecurring', 'otherItems', 'discontinuedOperations',\
           'preferredStockAndOtherAdjustments', 'otherOperatingExpense', 'taxProvision', 'interestIncome']

income_df_ = income_df.drop(dropCol, axis=1)[::-1]
income_df_.index = range(len(income_df_))
income_df_.columns = ['Date', 'totalRevenue', 'totalOperatingExpense',
       'costOfRevenue', 'grossProfit', 'ebit', 'netIncome',
       'researchAndDevelopment', 'incomeBeforeTax',
       'sellingGeneralAdministrative', 'otherNonOperatingIncome',
       'operatingIncome', 'interestExpense', 'incomeTaxExpense',
       'totalOtherIncomeExpense', 'netIncomeFromContinuingOperations',
       'netIncomeApplicableToCommonShares']

# income_df_.drop(['Date'], axis=1)/10000000000
income_df_2 = pd.concat([income_df_[['Date']], income_df_.drop(['Date'], axis=1).astype(float) / 10000000000], axis=1)

In [5]:
r2 = requests.get("https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol="+stockCode+"&apikey=" + api)

In [100]:
b = r2.json()['quarterlyReports']
balance_df = pd.DataFrame(b)

In [69]:
dropCol2 = ['reportedCurrency', 'intangibleAssets','earningAssets', 'deferredLongTermLiabilities',\
           'negativeGoodwill', 'warrants', 'preferredStockRedeemable', 'capitalSurplus',\
           'accumulatedDepreciation', 'goodwill', 'deferredLongTermAssetCharges', 'capitalLeaseObligations',\
           'treasuryStock', 'accumulatedAmortization', 'preferredStockTotalEquity', 'totalPermanentEquity', \
           'additionalPaidInCapital', 'currentLongTermDebt']

In [70]:
balance_df_ = balance_df.drop(dropCol2, axis=1)[::-1]
balance_df_.index = range(len(balance_df_))
balance_df_.columns = ['Date', 'totalAssets', 'otherCurrentAssets',
       'totalLiabilities', 'totalShareholderEquity', 'otherCurrentLiabilities',
       'commonStock', 'retainedEarnings', 'otherLiabilities', 'otherAssets',
       'cash', 'totalCurrentLiabilities', 'shortTermDebt',
       'otherShareholderEquity','propertyPlantEquipment', 'totalCurrentAssets', 'longTermInvestments',
       'netTangibleAssets', 'shortTermInvestments', 'netReceivables',
       'longTermDebt', 'inventory', 'accountsPayable',
       'commonStockTotalEquity',
       'retainedEarningsTotalEquity',
       'otherNonCurrrentAssets', 'totalNonCurrentAssets', 'totalLongTermDebt',
       'otherNonCurrentLiabilities', 'totalNonCurrentLiabilities',
       'liabilitiesAndShareholderEquity', 'cashAndShortTermInvestments',
       'commonStockSharesOutstanding']

In [99]:
# income_df_.drop(['Date'], axis=1)/10000000000
balance_df_2 = pd.concat([balance_df_[['Date']], balance_df_.drop(['Date'], axis=1).astype(float) / 10000000000], axis=1)

In [81]:
r3 = requests.get("https://www.alphavantage.co/query?function=CASH_FLOW&symbol="+stockCode+"&apikey=" + api)

In [98]:
c = r3.json()['quarterlyReports']
cash_df = pd.DataFrame(c)

In [86]:
findNone(cash_df)

['changeInOperatingActivities', 'changeInExchangeRate']

In [87]:
dropCol3 = ['reportedCurrency', 'changeInOperatingActivities', 'changeInExchangeRate']

In [101]:
cash_df_ = cash_df.drop(dropCol3, axis=1)[::-1]
cash_df_.index = range(len(cash_df_))

In [90]:
cash_df_.columns = ['Date', 'investments', 'changeInLiabilities',
       'cashflowFromInvestment', 'otherCashflowFromInvestment',
       'netBorrowings', 'cashflowFromFinancing', 'otherCashflowFromFinancing',
       'netIncome', 'changeInCash', 'operatingCashflow',
       'otherOperatingCashflow', 'depreciation', 'dividendPayout',
       'stockSaleAndPurchase', 'changeInInventory',
       'changeInAccountReceivables', 'changeInNetIncome',
       'capitalExpenditures', 'changeInReceivables',
       'changeInCashAndCashEquivalents']

In [97]:
cash_df_
# income_df_.drop(['Date'], axis=1)/10000000000
cash_df_2 = pd.concat([cash_df_[['Date']], cash_df_.drop(['Date'], axis=1).astype(float) / 10000000000], axis=1)

In [ ]:
income_df_2, balance_df_2, cash_df_2

In [96]:
result = pd.concat([income_df_2, balance_df_2.drop(['Date'], axis=1), cash_df_2.drop(['Date'], axis=1)], axis=1)

,Date,totalRevenue,totalOperatingExpense,costOfRevenue,grossProfit,ebit,netIncome,researchAndDevelopment,incomeBeforeTax,sellingGeneralAdministrative,...,otherOperatingCashflow,depreciation,dividendPayout,stockSaleAndPurchase,changeInInventory,changeInAccountReceivables,changeInNetIncome,capitalExpenditures,changeInReceivables,changeInCashAndCashEquivalents
0,2015-09-30,5.1501,0.5925,3.0953,2.0548,1.5062,1.1124,0.2220,1.5062,0.3705,...,-0.6200,0.3119,-0.2964,-1.3034,-0.0307,0.0417,-0.0523,0.3618,-0.6701,0.5801
1,2015-12-31,7.5324,0.6252,4.2495,3.0423,2.4573,1.8361,0.2404,2.4573,0.3848,...,0.0933,0.2954,-0.2969,-0.6862,-0.0102,0.5722,0.2670,0.3612,0.3896,-0.4431
2,2016-03-31,5.0557,0.5934,2.8159,1.9921,1.4142,1.0516,0.2511,1.4142,0.3423,...,0.5266,0.2477,-0.2902,-0.6421,0.0170,1.0519,0.2438,0.2336,0.0724,0.4825
3,2016-06-30,4.2358,0.6001,2.6252,1.6106,1.0469,0.7796,0.2560,1.0469,0.3441,...,-0.5056,0.2526,-0.3187,-1.0166,0.0450,1.1301,0.3153,0.2809,0.6681,-0.3277
4,2016-09-30,4.6852,0.6052,2.6491,1.7813,1.2188,0.9014,0.2570,1.2188,0.3482,...,-0.0053,0.2548,-0.3092,-0.5778,-0.0301,0.1044,0.0777,0.3977,-1.0257,0.2247
5,2016-12-31,7.8351,0.6817,4.5188,3.0176,2.4180,1.7891,0.2871,2.4180,0.3946,...,-0.1446,0.2987,-0.3130,-1.0851,-0.0580,0.1322,0.2434,0.3334,0.1322,-0.4113
6,2017-03-31,5.2896,0.6494,2.9973,2.0591,1.4684,1.1029,0.2776,1.4684,0.3718,...,0.0550,0.2332,-0.3004,-0.6888,-0.0198,0.8695,0.2652,0.2975,0.7373,-0.1214
7,2017-06-30,4.5408,0.6720,2.5566,1.7488,1.1308,0.8717,0.2937,1.1308,0.3783,...,-0.2333,0.2354,-0.3365,-0.7092,-0.0236,0.6693,0.3202,0.2277,-0.2002,0.3414
8,2017-09-30,5.2579,0.6811,3.0164,1.9931,1.3917,1.0714,0.2997,1.3917,0.3814,...,-0.2089,0.2484,-0.3270,-0.7514,-0.1709,-0.2093,0.2352,0.3865,-1.3040,0.1718
9,2017-12-31,8.8293,0.7638,5.1636,3.3912,2.6274,2.0065,0.3407,2.7030,0.4231,...,-0.0197,0.2745,-0.3339,-1.0095,0.0434,-0.5570,-3.2452,0.2810,-1.5230,0.7202
10,2018-03-31,6.1137,0.7528,3.7715,2.3422,1.5894,1.3822,0.3378,1.6168,0.4150,...,-0.0856,0.2739,-0.3190,-2.2429,-0.3241,0.9093,0.0710,0.4195,2.8468,1.7568
11,2018-06-30,5.3265,0.7809,3.2844,2.0421,1.2612,1.1519,0.3701,1.3284,0.4108,...,0.0988,0.2665,-0.3653,-2.0782,0.1693,0.0233,0.2218,0.3267,-0.3946,-1.3088
12,2018-09-30,6.2900,0.7966,3.8816,2.4084,1.6118,1.4125,0.3750,1.6421,0.4216,...,-0.0358,0.2754,-0.3530,-1.8763,0.1942,-0.9078,0.1830,0.3041,-2.2624,-0.6058
13,2018-12-31,8.4310,0.8685,5.2279,3.2031,2.3346,1.9965,0.3902,2.3906,0.4783,...,-0.1256,0.3395,-0.3568,-0.8796,-0.1076,0.5130,0.1558,0.3355,1.2035,1.8858
14,2019-03-31,5.8015,0.8406,3.6194,2.1821,1.3793,1.1561,0.3948,1.3793,0.4458,...,-0.0001,0.3040,-0.3443,-2.3702,0.0070,0.2964,0.1176,0.2363,1.0675,-0.4954
15,2019-06-30,5.3809,4.2265,3.3582,2.0227,1.5710,1.0044,0.4257,1.1911,0.4426,...,0.1174,0.2933,-0.3629,-1.6955,0.1502,0.0919,0.1457,0.2000,-0.0214,1.2334
16,2019-09-30,6.4040,4.8415,3.9727,2.4313,2.0116,1.3686,0.4110,1.6127,0.4578,...,0.0331,0.3179,-0.3479,-1.7444,-0.0785,-0.8768,0.0885,0.2777,-1.9320,-0.1927
17,2019-12-31,9.1819,0.9648,5.6602,3.5217,2.5918,2.2236,0.4451,2.5918,0.5197,...,-0.6069,0.2816,-0.3539,-2.0706,-0.0028,0.2015,0.1219,0.2107,0.5917,-0.8559
18,2020-03-31,5.8313,0.9517,3.5943,2.2370,1.3135,1.1249,0.4565,1.3135,0.4952,...,-0.1574,0.2786,-0.3375,-1.8574,0.0727,0.5269,0.1278,0.1853,0.9290,0.1384
19,2020-06-30,5.9685,0.9589,3.7005,2.2680,1.3137,1.1253,0.4758,1.3137,0.4831,...,0.2532,0.2752,-0.3656,-1.5891,-0.0689,-0.2135,0.2696,0.1565,-0.1373,-0.8010

In [104]:
result = pd.DataFrame()

In [106]:
pd.concat([income_df_2, balance_df_2.drop(['Date'], axis=1), cash_df_2.drop(['Date'], axis=1)], axis=1)

,Date,totalRevenue,totalOperatingExpense,costOfRevenue,grossProfit,ebit,netIncome,researchAndDevelopment,incomeBeforeTax,sellingGeneralAdministrative,...,otherOperatingCashflow,depreciation,dividendPayout,stockSaleAndPurchase,changeInInventory,changeInAccountReceivables,changeInNetIncome,capitalExpenditures,changeInReceivables,changeInCashAndCashEquivalents
0,2015-09-30,5.1501,0.5925,3.0953,2.0548,1.5062,1.1124,0.2220,1.5062,0.3705,...,-0.6200,0.3119,-0.2964,-1.3034,-0.0307,0.0417,-0.0523,0.3618,-0.6701,0.5801
1,2015-12-31,7.5324,0.6252,4.2495,3.0423,2.4573,1.8361,0.2404,2.4573,0.3848,...,0.0933,0.2954,-0.2969,-0.6862,-0.0102,0.5722,0.2670,0.3612,0.3896,-0.4431
2,2016-03-31,5.0557,0.5934,2.8159,1.9921,1.4142,1.0516,0.2511,1.4142,0.3423,...,0.5266,0.2477,-0.2902,-0.6421,0.0170,1.0519,0.2438,0.2336,0.0724,0.4825
3,2016-06-30,4.2358,0.6001,2.6252,1.6106,1.0469,0.7796,0.2560,1.0469,0.3441,...,-0.5056,0.2526,-0.3187,-1.0166,0.0450,1.1301,0.3153,0.2809,0.6681,-0.3277
4,2016-09-30,4.6852,0.6052,2.6491,1.7813,1.2188,0.9014,0.2570,1.2188,0.3482,...,-0.0053,0.2548,-0.3092,-0.5778,-0.0301,0.1044,0.0777,0.3977,-1.0257,0.2247
5,2016-12-31,7.8351,0.6817,4.5188,3.0176,2.4180,1.7891,0.2871,2.4180,0.3946,...,-0.1446,0.2987,-0.3130,-1.0851,-0.0580,0.1322,0.2434,0.3334,0.1322,-0.4113
6,2017-03-31,5.2896,0.6494,2.9973,2.0591,1.4684,1.1029,0.2776,1.4684,0.3718,...,0.0550,0.2332,-0.3004,-0.6888,-0.0198,0.8695,0.2652,0.2975,0.7373,-0.1214
7,2017-06-30,4.5408,0.6720,2.5566,1.7488,1.1308,0.8717,0.2937,1.1308,0.3783,...,-0.2333,0.2354,-0.3365,-0.7092,-0.0236,0.6693,0.3202,0.2277,-0.2002,0.3414
8,2017-09-30,5.2579,0.6811,3.0164,1.9931,1.3917,1.0714,0.2997,1.3917,0.3814,...,-0.2089,0.2484,-0.3270,-0.7514,-0.1709,-0.2093,0.2352,0.3865,-1.3040,0.1718
9,2017-12-31,8.8293,0.7638,5.1636,3.3912,2.6274,2.0065,0.3407,2.7030,0.4231,...,-0.0197,0.2745,-0.3339,-1.0095,0.0434,-0.5570,-3.2452,0.2810,-1.5230,0.7202
10,2018-03-31,6.1137,0.7528,3.7715,2.3422,1.5894,1.3822,0.3378,1.6168,0.4150,...,-0.0856,0.2739,-0.3190,-2.2429,-0.3241,0.9093,0.0710,0.4195,2.8468,1.7568
11,2018-06-30,5.3265,0.7809,3.2844,2.0421,1.2612,1.1519,0.3701,1.3284,0.4108,...,0.0988,0.2665,-0.3653,-2.0782,0.1693,0.0233,0.2218,0.3267,-0.3946,-1.3088
12,2018-09-30,6.2900,0.7966,3.8816,2.4084,1.6118,1.4125,0.3750,1.6421,0.4216,...,-0.0358,0.2754,-0.3530,-1.8763,0.1942,-0.9078,0.1830,0.3041,-2.2624,-0.6058
13,2018-12-31,8.4310,0.8685,5.2279,3.2031,2.3346,1.9965,0.3902,2.3906,0.4783,...,-0.1256,0.3395,-0.3568,-0.8796,-0.1076,0.5130,0.1558,0.3355,1.2035,1.8858
14,2019-03-31,5.8015,0.8406,3.6194,2.1821,1.3793,1.1561,0.3948,1.3793,0.4458,...,-0.0001,0.3040,-0.3443,-2.3702,0.0070,0.2964,0.1176,0.2363,1.0675,-0.4954
15,2019-06-30,5.3809,4.2265,3.3582,2.0227,1.5710,1.0044,0.4257,1.1911,0.4426,...,0.1174,0.2933,-0.3629,-1.6955,0.1502,0.0919,0.1457,0.2000,-0.0214,1.2334
16,2019-09-30,6.4040,4.8415,3.9727,2.4313,2.0116,1.3686,0.4110,1.6127,0.4578,...,0.0331,0.3179,-0.3479,-1.7444,-0.0785,-0.8768,0.0885,0.2777,-1.9320,-0.1927
17,2019-12-31,9.1819,0.9648,5.6602,3.5217,2.5918,2.2236,0.4451,2.5918,0.5197,...,-0.6069,0.2816,-0.3539,-2.0706,-0.0028,0.2015,0.1219,0.2107,0.5917,-0.8559
18,2020-03-31,5.8313,0.9517,3.5943,2.2370,1.3135,1.1249,0.4565,1.3135,0.4952,...,-0.1574,0.2786,-0.3375,-1.8574,0.0727,0.5269,0.1278,0.1853,0.9290,0.1384
19,2020-06-30,5.9685,0.9589,3.7005,2.2680,1.3137,1.1253,0.4758,1.3137,0.4831,...,0.2532,0.2752,-0.3656,-1.5891,-0.0689,-0.2135,0.2696,0.1565,-0.1373,-0.8010

In [107]:
cash_df

,fiscalDateEnding,reportedCurrency,investments,changeInLiabilities,cashflowFromInvestment,otherCashflowFromInvestment,netBorrowings,cashflowFromFinancing,otherCashflowFromFinancing,changeInOperatingActivities,...,depreciation,dividendPayout,stockSaleAndPurchase,changeInInventory,changeInAccountReceivables,changeInNetIncome,capitalExpenditures,changeInReceivables,changeInExchangeRate,changeInCashAndCashEquivalents
0,2020-06-30,USD,-5165000000,3159000000,-5165000000,-263000000,2168000000,-19116000000,-69000000,-765000000,...,2752000000,-3656000000,-15891000000,-689000000,-2135000000,2696000000,1565000000,-1373000000,None,-8010000000
1,2020-03-31,USD,9013000000,-12193000000,9013000000,-296000000,803000000,-20940000000,-35000000,4195000000,...,2786000000,-3375000000,-18574000000,727000000,5269000000,1278000000,1853000000,9290000000,None,1384000000
2,2019-12-31,USD,-13668000000,-104000000,-13668000000,-130000000,231000000,-25407000000,-16000000,2362000000,...,2816000000,-3539000000,-20706000000,-28000000,2015000000,1219000000,2107000000,5917000000,None,-8559000000
3,2019-09-30,USD,-798000000,18032000000,-798000000,-810000000,-293000000,-21039000000,-22000000,-6319000000,...,3179000000,-3479000000,-17444000000,-785000000,-8768000000,885000000,2777000000,-19320000000,None,-1927000000
4,2019-06-30,USD,27502000000,-5260000000,27502000000,-618000000,-5026000000,-26804000000,-1195000000,-5203000000,...,2933000000,-3629000000,-16955000000,1502000000,919000000,1457000000,2000000000,-214000000,None,12334000000
5,2019-03-31,USD,15749000000,-15366000000,13348000000,-38000000,-2506000000,-29457000000,-196000000,4037000000,...,3040000000,-3443000000,-23702000000,70000000,2964000000,1176000000,2363000000,10675000000,None,-4954000000
6,2018-12-31,USD,9422000000,-7931000000,5844000000,-223000000,6000000,-13676000000,-1318000000,6589000000,...,3395000000,-3568000000,-8796000000,-1076000000,5130000000,1558000000,3355000000,12035000000,None,18858000000
7,2018-09-30,USD,552000000,20373000000,-3001000000,-512000000,-27000000,-22580000000,-260000000,-12423000000,...,2754000000,-3530000000,-18763000000,1942000000,-9078000000,1830000000,3041000000,-22624000000,None,-6058000000
8,2018-06-30,USD,7916000000,-649000000,3947000000,-702000000,-6011000000,-31523000000,-1077000000,-5340000000,...,2665000000,-3653000000,-20782000000,1693000000,233000000,2218000000,3267000000,-3946000000,None,-13088000000
9,2018-03-31,USD,32894000000,-28121000000,28710000000,11000000,-501000000,-26272000000,-152000000,20128000000,...,2739000000,-3190000000,-22429000000,-3241000000,9093000000,710000000,4195000000,28468000000,None,17568000000
10,2017-12-31,USD,-10517000000,52928000000,-13590000000,-263000000,6971000000,-7501000000,-1038000000,27692000000,...,2745000000,-3339000000,-10095000000,434000000,-5570000000,-32452000000,2810000000,-15230000000,None,7202000000
11,2017-09-30,USD,-5768000000,16944000000,-9942000000,-309000000,6923000000,-3996000000,-135000000,-8447000000,...,2484000000,-3270000000,-7514000000,-1709000000,-2093000000,2352000000,3865000000,-13040000000,None,1718000000
12,2017-06-30,USD,-836000000,-1339000000,-3180000000,-67000000,9237000000,-1769000000,-549000000,-6325000000,...,2354000000,-3365000000,-7092000000,-236000000,6693000000,3202000000,2277000000,-2002000000,None,3414000000
13,2017-03-31,USD,-11357000000,-11393000000,-14202000000,130000000,10469000000,465000000,-112000000,550000000,...,2332000000,-3004000000,-6888000000,-198000000,8695000000,2652000000,2975000000,7373000000,None,-1214000000
14,2016-12-31,USD,-15581000000,4448000000,-19122000000,-207000000,2385000000,-12047000000,-451000000,-1446000000,...,2987000000,-3130000000,-10851000000,-580000000,1322000000,2434000000,3334000000,1322000000,None,-4113000000
15,2016-09-30,USD,-3419000000,14398000000,-7397000000,-1000000,2581000000,-6482000000,-193000000,-902000000,...,2548000000,-3092000000,-5778000000,-301000000,1044000000,777000000,3977000000,-10257000000,None,2247000000
16,2016-06-30,USD,-1434000000,-4804000000,-4470000000,-101000000,4395000000,-9441000000,-483000000,957000000,...,2526000000,-3187000000,-10166000000,450000000,11301000000,3153000000,2809000000,6681000000,None,-3277000000
17,2016-03-31,USD,-10857000000,-10155000000,-13660000000,-341000000,16321000000,6884000000,-114000000,1358000000,...,2477000000,-2902000000,-6421000000,170000000,10519000000,2438000000,2336000000,724000000,None,4825000000
18,2015-12-31,USD,-16060000000,-1249000000,-20450000000,-778000000,-1240000000,-11444000000,-373000000,None,...,2954000000,-2969000000,-6862000000,-102000000,5722000000,2670000000,3612000000,3896000000,None,-4431000000
19,2015-09-30,USD,2556000000,12963000000,-1375000000,-313000000,9801000000,-6299000000,-102000000,5040000000,...,3119000000,-2964000000,-13034000000,-307000000,417000000,-523000000,3618000000,-6701000000,None,5801000000