In [1]:
# get fundamental data
import requests

stockCode = 'AAPL'

# set api key
api = "7OVAOOPNIMKJKIAX"

r = requests.get("https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol="+stockCode+"&apikey=" + api)

In [ ]:
def findNone(balance_df_):
    for i in balance_df_.columns:
        for j in balance_df_[i]:
            if 'None' in j:
                print(i)

In [3]:
a = r.json()['quarterlyReports']

In [4]:
import pandas as pd

income_df = pd.DataFrame(a)
dropCol = ['reportedCurrency', 'effectOfAccountingCharges','minorityInterest', 'netInterestIncome',\
           'extraordinaryItems', 'nonRecurring', 'otherItems', 'discontinuedOperations',\
           'preferredStockAndOtherAdjustments', 'otherOperatingExpense', 'taxProvision', 'interestIncome']

income_df_ = income_df.drop(dropCol, axis=1)[::-1]
income_df_.index = range(len(income_df_))
income_df_.columns = ['Date', 'totalRevenue', 'totalOperatingExpense',
       'costOfRevenue', 'grossProfit', 'ebit', 'netIncome',
       'researchAndDevelopment', 'incomeBeforeTax',
       'sellingGeneralAdministrative', 'otherNonOperatingIncome',
       'operatingIncome', 'interestExpense', 'incomeTaxExpense',
       'totalOtherIncomeExpense', 'netIncomeFromContinuingOperations',
       'netIncomeApplicableToCommonShares']

# income_df_.drop(['Date'], axis=1)/10000000000
income_df_2 = pd.concat([income_df_[['Date']], income_df_.drop(['Date'], axis=1).astype(float) / 10000000000], axis=1)
income_df_2

,Date,totalRevenue,totalOperatingExpense,costOfRevenue,grossProfit,ebit,netIncome,researchAndDevelopment,incomeBeforeTax,sellingGeneralAdministrative,otherNonOperatingIncome,operatingIncome,interestExpense,incomeTaxExpense,totalOtherIncomeExpense,netIncomeFromContinuingOperations,netIncomeApplicableToCommonShares
0,2015-09-30,5.1501,0.5925,3.0953,2.0548,1.5062,1.1124,0.2220,1.5062,0.3705,0.0439,1.4623,0.0238,0.3938,0.0895,1.1124,1.1124
1,2015-12-31,7.5324,0.6252,4.2495,3.0423,2.4573,1.8361,0.2404,2.4573,0.3848,0.0402,2.3623,0.0276,0.6212,0.0402,1.8361,1.8361
2,2016-03-31,5.0557,0.5934,2.8159,1.9921,1.4142,1.0516,0.2511,1.4142,0.3423,0.0155,1.3987,0.0321,0.3626,-0.0247,1.0516,1.0516
3,2016-06-30,4.2358,0.6001,2.6252,1.6106,1.0469,0.7796,0.2560,1.0469,0.3441,0.0364,1.0105,0.0409,0.2673,0.0209,0.7796,0.7796
4,2016-09-30,4.6852,0.6052,2.6491,1.7813,1.2188,0.9014,0.2570,1.2188,0.3482,0.0427,1.1761,0.0450,0.3174,0.0984,0.9014,0.9014
5,2016-12-31,7.8351,0.6817,4.5188,3.0176,2.4180,1.7891,0.2871,2.4180,0.3946,0.0821,2.3359,0.0525,0.6289,0.0821,1.7891,1.7891
6,2017-03-31,5.2896,0.6494,2.9973,2.0591,1.4684,1.1029,0.2776,1.4684,0.3718,0.0587,1.4097,0.0530,0.3655,-0.0234,1.1029,1.1029
7,2017-06-30,4.5408,0.6720,2.5566,1.7488,1.1308,0.8717,0.2937,1.1308,0.3783,0.0540,1.0768,0.0602,0.2591,-0.0047,0.8717,0.8717
8,2017-09-30,5.2579,0.6811,3.0164,1.9931,1.3917,1.0714,0.2997,1.3917,0.3814,0.0797,1.3120,0.0666,0.3203,0.2205,1.0714,1.0714
9,2017-12-31,8.8293,0.7638,5.1636,3.3912,2.6274,2.0065,0.3407,2.7030,0.4231,0.0756,2.6274,0.0734,0.6965,0.0756,2.0065,2.0065
10,2018-03-31,6.1137,0.7528,3.7715,2.3422,1.5894,1.3822,0.3378,1.6168,0.4150,0.0274,1.5894,-0.0792,0.2346,0.0274,1.3822,1.3822
11,2018-06-30,5.3265,0.7809,3.2844,2.0421,1.2612,1.1519,0.3701,1.3284,0.4108,0.0672,1.2612,-0.0846,0.1765,0.0672,1.1519,1.1519
12,2018-09-30,6.2900,0.7966,3.8816,2.4084,1.6118,1.4125,0.3750,1.6421,0.4216,0.0303,1.6118,-0.0868,0.2296,0.0303,1.4125,1.4125
13,2018-12-31,8.4310,0.8685,5.2279,3.2031,2.3346,1.9965,0.3902,2.3906,0.4783,0.0560,2.3346,-0.0890,0.3941,0.0560,1.9965,1.9965
14,2019-03-31,5.8015,0.8406,3.6194,2.1821,1.3793,1.1561,0.3948,1.3793,0.4458,0.0378,1.3415,0.1010,0.2232,0.0030,1.1561,1.1561
15,2019-06-30,5.3809,4.2265,3.3582,2.0227,1.5710,1.0044,0.4257,1.1911,0.4426,0.0367,1.1544,0.0866,0.1867,0.0043,1.0044,1.0044
16,2019-09-30,6.4040,4.8415,3.9727,2.4313,2.0116,1.3686,0.4110,1.6127,0.4578,0.0502,1.5625,0.0810,0.2441,0.0206,1.3686,1.3686
17,2019-12-31,9.1819,0.9648,5.6602,3.5217,2.5918,2.2236,0.4451,2.5918,0.5197,0.0349,2.5569,0.0785,0.3682,0.0089,2.2236,2.2236
18,2020-03-31,5.8313,0.9517,3.5943,2.2370,1.3135,1.1249,0.4565,1.3135,0.4952,0.0282,1.2853,0.0757,0.1886,-0.0010,1.1249,1.1249
19,2020-06-30,5.9685,0.9589,3.7005,2.2680,1.3137,1.1253,0.4758,1.3137,0.4831,0.0046,1.3091,0.0697,0.1884,-0.0158,1.1253,1.1253

In [5]:
r2 = requests.get("https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol="+stockCode+"&apikey=" + api)

In [8]:
b = r2.json()['quarterlyReports']
balance_df = pd.DataFrame(b)
balance_df

,fiscalDateEnding,reportedCurrency,totalAssets,intangibleAssets,earningAssets,otherCurrentAssets,totalLiabilities,totalShareholderEquity,deferredLongTermLiabilities,otherCurrentLiabilities,...,otherNonCurrentLiabilities,totalNonCurrentLiabilities,negativeGoodwill,warrants,preferredStockRedeemable,capitalSurplus,liabilitiesAndShareholderEquity,cashAndShortTermInvestments,accumulatedDepreciation,commonStockSharesOutstanding
0,2020-06-30,USD,317344000000,None,None,10987000000,245062000000,72282000000,None,35005000000,...,27508000000,149744000000,None,None,None,None,317344000000,93025000000,None,4283939000
1,2020-03-31,USD,320400000000,None,None,15691000000,241975000000,78425000000,None,37324000000,...,28607000000,145881000000,None,None,None,None,320400000000,94051000000,None,4323987000
2,2019-12-31,USD,340618000000,None,None,12026000000,251087000000,89531000000,None,36263000000,...,27650000000,148926000000,None,None,None,None,340618000000,107162000000,None,4384959000
3,2019-09-30,USD,338516000000,None,None,12352000000,248028000000,90488000000,None,37720000000,...,20958000000,142310000000,None,None,None,None,338516000000,100557000000,None,4649000000
4,2019-06-30,USD,322239000000,None,None,10530000000,225783000000,96456000000,None,31673000000,...,20622000000,136079000000,None,None,None,None,322239000000,94614000000,None,4601000000
5,2019-03-31,USD,341998000000,None,None,12092000000,236138000000,105860000000,None,40900000000,...,52165000000,142366000000,None,None,None,None,341998000000,80092000000,None,4701000000
6,2018-12-31,USD,373719000000,None,None,12432000000,255827000000,117892000000,None,42249000000,...,54555000000,147544000000,None,None,None,None,373719000000,86427000000,None,4773000000
7,2018-09-30,USD,365725000000,0,None,12087000000,258578000000,107147000000,2797000000,40230000000,...,45180000000,141712000000,None,None,None,None,365725000000,66301000000,None,5000000000
8,2018-06-30,USD,349197000000,0,None,12488000000,234248000000,114949000000,2878000000,7403000000,...,45694000000,145700000000,None,None,None,None,349197000000,70970000000,None,4927000000
9,2018-03-31,USD,367502000000,0,None,12043000000,240624000000,126878000000,3087000000,7775000000,...,46855000000,151304000000,None,None,None,None,367502000000,87940000000,None,5068000000
10,2017-12-31,USD,406794000000,2149000000,None,11337000000,266595000000,140199000000,3131000000,8044000000,...,43754000000,150807000000,None,None,None,None,406794000000,77153000000,None,5158000000
11,2017-09-30,USD,375319000000,2298000000,None,13936000000,241272000000,134047000000,2836000000,7548000000,...,40415000000,140458000000,None,None,None,None,375319000000,74181000000,None,5252000000
12,2017-06-30,USD,345173000000,2444000000,None,10338000000,212748000000,132425000000,2984000000,7608000000,...,38598000000,131446000000,None,None,None,None,345173000000,76759000000,None,5233000000
13,2017-03-31,USD,334532000000,2617000000,None,11367000000,200450000000,134082000000,3107000000,7682000000,...,39470000000,127108000000,None,None,None,None,334532000000,67101000000,None,5262000000
14,2016-12-31,USD,331141000000,2848000000,None,12191000000,198751000000,132390000000,3163000000,7889000000,...,37901000000,114621000000,None,None,None,None,331141000000,60452000000,None,5328000000
15,2016-09-30,USD,321686000000,3206000000,None,8283000000,193437000000,128249000000,2930000000,8080000000,...,36074000000,114431000000,None,None,None,None,321686000000,67155000000,None,5500000000
16,2016-06-30,USD,305602000000,3506000000,None,11132000000,179061000000,126541000000,3064000000,8352000000,...,35572000000,107575000000,None,None,None,None,305602000000,61756000000,None,5473000000
17,2016-03-31,USD,305277000000,3843000000,None,10204000000,174820000000,130457000000,3322000000,9461000000,...,33859000000,106555000000,None,None,None,None,305277000000,55283000000,None,5541000000
18,2015-12-31,USD,293284000000,3924000000,None,11073000000,165017000000,128267000000,3546000000,8989000000,...,32175000000,88925000000,None,None,None,None,293284000000,38074000000,None,5594000000
19,2015-09-30,USD,290479000000,3893000000,None,9539000000,171124000000,119355000000,3624000000,8940000000,...,33427000000,90514000000,None,None,None,None,290479000000,41601000000,None,5793000000

In [69]:
dropCol2 = ['reportedCurrency', 'intangibleAssets','earningAssets', 'deferredLongTermLiabilities',\
           'negativeGoodwill', 'warrants', 'preferredStockRedeemable', 'capitalSurplus',\
           'accumulatedDepreciation', 'goodwill', 'deferredLongTermAssetCharges', 'capitalLeaseObligations',\
           'treasuryStock', 'accumulatedAmortization', 'preferredStockTotalEquity', 'totalPermanentEquity', \
           'additionalPaidInCapital', 'currentLongTermDebt']

In [70]:
balance_df_ = balance_df.drop(dropCol2, axis=1)[::-1]
balance_df_.index = range(len(balance_df_))
balance_df_.columns = ['Date', 'totalAssets', 'otherCurrentAssets',
       'totalLiabilities', 'totalShareholderEquity', 'otherCurrentLiabilities',
       'commonStock', 'retainedEarnings', 'otherLiabilities', 'otherAssets',
       'cash', 'totalCurrentLiabilities', 'shortTermDebt',
       'otherShareholderEquity','propertyPlantEquipment', 'totalCurrentAssets', 'longTermInvestments',
       'netTangibleAssets', 'shortTermInvestments', 'netReceivables',
       'longTermDebt', 'inventory', 'accountsPayable',
       'commonStockTotalEquity',
       'retainedEarningsTotalEquity',
       'otherNonCurrrentAssets', 'totalNonCurrentAssets', 'totalLongTermDebt',
       'otherNonCurrentLiabilities', 'totalNonCurrentLiabilities',
       'liabilitiesAndShareholderEquity', 'cashAndShortTermInvestments',
       'commonStockSharesOutstanding']

In [71]:
# income_df_.drop(['Date'], axis=1)/10000000000
balance_df_2 = pd.concat([balance_df_[['Date']], balance_df_.drop(['Date'], axis=1).astype(float) / 10000000000], axis=1)
balance_df_2

,Date,totalAssets,otherCurrentAssets,totalLiabilities,totalShareholderEquity,otherCurrentLiabilities,commonStock,retainedEarnings,otherLiabilities,otherAssets,...,commonStockTotalEquity,retainedEarningsTotalEquity,otherNonCurrrentAssets,totalNonCurrentAssets,totalLongTermDebt,otherNonCurrentLiabilities,totalNonCurrentLiabilities,liabilitiesAndShareholderEquity,cashAndShortTermInvestments,commonStockSharesOutstanding
0,2015-09-30,29.0479,0.9539,17.1124,11.9355,0.8940,2.7416,9.1939,1.2989,17.8630,...,2.7416,9.2284,0.5556,20.1101,5.3463,3.3427,9.0514,29.0479,4.1601,0.579300
1,2015-12-31,29.3284,1.1073,16.5017,12.8267,0.8989,2.8253,10.0014,1.4104,19.4765,...,2.8253,10.1494,0.7974,21.7065,5.3204,3.2175,8.8925,29.3284,3.8074,0.559400
2,2016-03-31,30.5277,1.0204,17.4820,13.0457,0.9461,2.9484,10.0973,1.4226,19.4482,...,2.9484,10.2021,0.7745,21.7685,6.9374,3.3859,10.6555,30.5277,5.5283,0.554100
3,2016-06-30,30.5602,1.1132,17.9061,12.6541,0.8352,3.0106,9.6435,1.4076,18.6393,...,3.0106,9.6542,0.7862,21.1841,6.8939,3.5572,10.7575,30.5602,6.1756,0.547300
4,2016-09-30,32.1686,0.8283,19.3437,12.8249,0.8080,3.1251,9.6998,1.2985,18.7807,...,3.1251,9.6364,0.8757,21.4817,7.5427,3.6074,11.4431,32.1686,6.7155,0.550000
5,2016-12-31,33.1141,1.2191,19.8751,13.2390,0.7889,3.2144,10.0246,1.4116,20.1299,...,3.2144,10.0001,0.7390,22.7809,7.3557,3.7901,11.4621,33.1141,6.0452,0.532800
6,2017-03-31,33.4532,1.1367,20.0450,13.4082,0.7682,3.3579,10.0503,1.4351,20.5379,...,3.3579,10.0925,0.7549,23.2542,8.4531,3.9470,12.7108,33.4532,6.7101,0.526200
7,2017-06-30,34.5173,1.0338,21.2748,13.2425,0.7608,3.4445,9.7980,1.1391,20.3012,...,3.4445,9.8525,1.0150,23.2298,8.9864,3.8598,13.1446,34.5173,7.6759,0.523300
8,2017-09-30,37.5319,1.3936,24.1272,13.4047,0.7548,3.5867,9.8180,1.1747,21.2891,...,3.5867,9.8330,1.0162,24.6674,9.7207,4.0415,14.0458,37.5319,7.4181,0.525200
9,2017-12-31,40.6794,1.1337,26.6595,14.0199,0.8044,3.6447,10.3752,4.6337,22.9305,...,3.6447,10.4593,1.3323,26.2984,10.3922,4.3754,15.0807,40.6794,7.7153,0.515800
10,2018-03-31,36.7502,1.2043,24.0624,12.6878,0.7775,3.8044,9.1898,4.9942,2.3086,...,3.8044,9.1898,2.3086,23.7449,10.1362,4.6855,15.1304,36.7502,8.7940,0.506800
11,2018-06-30,34.9197,1.2488,23.4248,11.4949,0.7403,3.8624,7.9436,4.8572,2.2546,...,3.8624,7.9436,2.2546,23.3436,9.7128,4.5694,14.5700,34.9197,7.0970,0.492700
12,2018-09-30,36.5725,1.2087,25.8578,10.7147,4.0230,4.0201,7.0400,4.7977,2.2283,...,4.0201,7.0400,2.2283,23.4386,9.3735,4.5180,14.1712,36.5725,6.6301,0.500000
13,2018-12-31,37.3719,1.2432,25.5827,11.7892,4.2249,4.0970,8.0510,5.4555,3.4686,...,4.0970,8.0510,3.4686,23.2891,9.2989,5.4555,14.7544,37.3719,8.6427,0.477300
14,2019-03-31,34.1998,1.2092,23.6138,10.5860,4.0900,4.2801,6.4558,5.2165,3.4587,...,4.2801,6.4558,3.4587,21.8652,9.0201,5.2165,14.2366,34.1998,8.0092,0.470100
15,2019-06-30,32.2239,1.0530,22.5783,9.6456,3.1673,4.3371,5.3724,5.1143,3.3634,...,4.3371,5.3724,3.3634,18.7266,8.4936,2.0622,13.6079,32.2239,9.4614,0.460100
16,2019-09-30,33.8516,1.2352,24.8028,9.0488,3.7720,4.5174,4.5898,5.0503,3.2978,...,4.5174,4.5898,3.2978,17.5697,9.1807,2.0958,14.2310,33.8516,10.0557,0.464900
17,2019-12-31,34.0618,1.2026,25.1087,8.9531,3.6263,4.5972,4.3977,4.8648,3.3195,...,4.5972,4.3977,4.0457,17.7387,9.3078,2.7650,14.8926,34.0618,10.7162,0.438496
18,2020-03-31,32.0400,1.5691,24.1975,7.8425,3.7324,4.8032,3.3182,4.8745,3.3868,...,4.8032,3.3182,4.1965,17.6647,8.9086,2.8607,14.5881,32.0400,9.4051,0.432399
19,2020-06-30,31.7344,1.0987,24.5062,7.2282,3.5005,4.8696,2.4136,4.7606,3.2836,...,4.8696,2.4136,4.1000,17.7279,9.4048,2.7508,14.9744,31.7344,9.3025,0.428394

In [31]:
balance_df_.columns

Index(['Date', 'totalAssets', 'otherCurrentAssets', 'totalLiabilities',
       'totalShareholderEquity', 'otherCurrentLiabilities', 'commonStock',
       'retainedEarnings', 'otherLiabilities', 'otherAssets', 'cash',
       'totalCurrentLiabilities', 'shortTermDebt', 'currentLongTermDebt',
       'otherShareholderEquity', 'propertyPlantEquipment',
       'totalCurrentAssets', 'longTermInvestments', 'netTangibleAssets',
       'shortTermInvestments', 'netReceivables', 'longTermDebt', 'inventory',
       'accountsPayable', 'totalPermanentEquity', 'additionalPaidInCapital',
       'commonStockTotalEquity', 'retainedEarningsTotalEquity',
       'otherNonCurrrentAssets', 'totalNonCurrentAssets', 'totalLongTermDebt',
       'otherNonCurrentLiabilities', 'totalNonCurrentLiabilities',
       'liabilitiesAndShareholderEquity', 'cashAndShortTermInvestments',
       'commonStockSharesOutstanding'],
      dtype='object')

In [61]:
balance_df_['otherNonCurrrentAssets']

0      5556000000
1      7974000000
2      7745000000
3      7862000000
4      8757000000
5      7390000000
6      7549000000
7     10150000000
8     10162000000
9     13323000000
10    23086000000
11    22546000000
12    22283000000
13    34686000000
14    34587000000
15    33634000000
16    32978000000
17    40457000000
18    41965000000
19    41000000000
Name: otherNonCurrrentAssets, dtype: object

currentLongTermDebt

In [65]:
for i in balance_df['goodwill']:
    if 'None' in i:
        print(i)

None
None
None
None
None
None
None